"""portal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views. Home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls')
"""
from django.urls import path

from main_app.EditResultView import EditResultView

from .views import increment_view, get_view_count


from .views import export_single_device_excel

from . import hod_views, staff_views, sugar_views, views, kh_views, holding_views, piran_views, tomato_views, \
    taraghi_views, tootia_views, drug_views, gen_views, iron_views, ptro_views, agriculture_views, research_views, \
    all_views, person_views



urlpatterns = [
     path('device/export/<int:device_id>/', export_single_device_excel, name='export_single_device_excel'),
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("organ/add", hod_views.add_organ, name='add_organ'),
    path("send_sugar_notification/", hod_views.send_sugar_notification,
         name='send_sugar_notification'),
    path("send_kh_notification/", hod_views.send_kh_notification,
         name='send_kh_notification'),
    path("send_person_notification/", hod_views.send_person_notification,
         name='send_person_notification'),
    path("send_holding_notification/", hod_views.send_holding_notification,
         name='send_holding_notification'),
    path("send_piran_notification/", hod_views.send_piran_notification,
         name='send_piran_notification'),
    path("send_tomato_notification/", hod_views.send_tomato_notification,
         name='send_tomato_notification'),
    path("send_taraghi_notification/", hod_views.send_taraghi_notification,
         name='send_taraghi_notification'),
    path("send_tootia_notification/", hod_views.send_tootia_notification,
         name='send_tootia_notification'),
    path("send_drug_notification/", hod_views.send_drug_notification,
         name='send_drug_notification'),
    path("send_gen_notification/", hod_views.send_gen_notification,
         name='send_gen_notification'),
    path("send_iron_notification/", hod_views.send_iron_notification,
         name='send_iron_notification'),
    path("send_ptro_notification/", hod_views.send_ptro_notification,
         name='send_ptro_notification'),
    path("send_agriculture_notification/", hod_views.send_agriculture_notification,
         name='send_agriculture_notification'),
    path("send_research_notification/", hod_views.send_research_notification,
         name='send_research_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", hod_views.add_session, name='add_session'),
    path("admin_notify_sugar", hod_views.admin_notify_sugar,
         name='admin_notify_sugar'),
    path("admin_notify_kh", hod_views.admin_notify_kh,
         name='admin_notify_kh'),
    path("admin_notify_person", hod_views.admin_notify_person,
         name='admin_notify_person'),
    path("admin_notify_holding", hod_views.admin_notify_holding,
         name='admin_notify_holding'),
    path("admin_notify_piran", hod_views.admin_notify_piran,
         name='admin_notify_piran'),
    path("admin_notify_tomato", hod_views.admin_notify_tomato,
         name='admin_notify_tomato'),
    path("admin_notify_taraghi", hod_views.admin_notify_taraghi,
         name='admin_notify_taraghi'),
    path("admin_notify_tootia", hod_views.admin_notify_tootia,
         name='admin_notify_tootia'),
    path("admin_notify_drug", hod_views.admin_notify_drug,
         name='admin_notify_drug'),
    path("admin_notify_gen", hod_views.admin_notify_gen,
         name='admin_notify_gen'),
    path("admin_notify_iron", hod_views.admin_notify_iron,
         name='admin_notify_iron'),
    path("admin_notify_ptro", hod_views.admin_notify_ptro,
         name='admin_notify_ptro'),
    path("admin_notify_agriculture", hod_views.admin_notify_agriculture,
         name='admin_notify_agriculture'),
    path("admin_notify_research", hod_views.admin_notify_research,
         name='admin_notify_research'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    path("sugar/view/feedback/", hod_views.sugar_feedback_message,
         name="sugar_feedback_message", ),
    path("kh/view/feedback/", hod_views.kh_feedback_message,
         name="kh_feedback_message", ),
    path("person/view/feedback/", hod_views.person_feedback_message,
         name="person_feedback_message", ),
    path("holding/view/feedback/", hod_views.holding_feedback_message,
         name="holding_feedback_message", ),
    path("piran/view/feedback/", hod_views.piran_feedback_message,
         name="piran_feedback_message", ),
    path("tomato/view/feedback/", hod_views.tomato_feedback_message,
         name="tomato_feedback_message", ),
    path("taraghi/view/feedback/", hod_views.taraghi_feedback_message,
         name="taraghi_feedback_message", ),
    path("tootia/view/feedback/", hod_views.tootia_feedback_message,
         name="tootia_feedback_message", ),
    path("drug/view/feedback/", hod_views.drug_feedback_message,
         name="drug_feedback_message", ),
    path("gen/view/feedback/", hod_views.gen_feedback_message,
         name="gen_feedback_message", ),
    path("iron/view/feedback/", hod_views.iron_feedback_message,
         name="iron_feedback_message", ),
    path("ptro/view/feedback/", hod_views.ptro_feedback_message,
         name="ptro_feedback_message", ),
    path("agriculture/view/feedback/", hod_views.agriculture_feedback_message,
         name="agriculture_feedback_message", ),
    path("research/view/feedback/", hod_views.research_feedback_message,
         name="research_feedback_message", ),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message", ),
    path("sugar/view/leave/", hod_views.view_sugar_leave,
         name="view_sugar_leave", ),
    path("kh/view/leave/", hod_views.view_kh_leave,
         name="view_kh_leave", ),
    path("person/view/leave/", hod_views.view_person_leave,
         name="view_person_leave", ),
    path("holding/view/leave/", hod_views.view_holding_leave,
         name="view_holding_leave", ),
    path("piran/view/leave/", hod_views.view_piran_leave,
         name="view_piran_leave", ),
    path("tomato/view/leave/", hod_views.view_tomato_leave,
         name="view_tomato_leave", ),
    path("taraghi/view/leave/", hod_views.view_taraghi_leave,
         name="view_taraghi_leave", ),
    path("tootia/view/leave/", hod_views.view_tootia_leave,
         name="view_tootia_leave", ),
    path("drug/view/leave/", hod_views.view_drug_leave,
         name="view_drug_leave", ),
    path("gen/view/leave/", hod_views.view_gen_leave,
         name="view_gen_leave", ),
    path("iron/view/leave/", hod_views.view_iron_leave,
         name="view_iron_leave", ),
    path("ptro/view/leave/", hod_views.view_ptro_leave,
         name="view_ptro_leave", ),
    path("agriculture/view/leave/", hod_views.view_agriculture_leave,
         name="view_agriculture_leave", ),
    path("research/view/leave/", hod_views.view_research_leave,
         name="view_research_leave", ),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave", ),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance", ),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("sugar/add/", hod_views.add_sugar, name='add_sugar'),
    path("kh/add/", hod_views.add_kh, name='add_kh'),
    path("person/add/", hod_views.add_person, name='add_person'),
    path("holding/add/", hod_views.add_holding, name='add_holding'),
    path("piran/add/", hod_views.add_piran, name='add_piran'),
    path("tomato/add/", hod_views.add_tomato, name='add_tomato'),
    path("taraghi/add/", hod_views.add_taraghi, name='add_taraghi'),
    path("tootia/add/", hod_views.add_tootia, name='add_tootia'),
    path("drug/add/", hod_views.add_drug, name='add_drug'),
    path("gen/add/", hod_views.add_gen, name='add_gen'),
    path("iron/add/", hod_views.add_iron, name='add_iron'),
    path("ptro/add/", hod_views.add_ptro, name='add_ptro'),
    path("agriculture/add/", hod_views.add_agriculture, name='add_agriculture'),
    path("research/add/", hod_views.add_research, name='add_research'),
    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("sugar/manage/", hod_views.manage_sugar, name='manage_sugar'),
    path("kh/manage/", hod_views.manage_kh, name='manage_kh'),
    path("person/manage/", hod_views.manage_person, name='manage_person'),
    path("holding/manage/", hod_views.manage_holding, name='manage_holding'),
    path("piran/manage/", hod_views.manage_piran, name='manage_piran'),
    path("tomato/manage/", hod_views.manage_tomato, name='manage_tomato'),
    path("taraghi/manage/", hod_views.manage_taraghi, name='manage_taraghi'),
    path("tootia/manage/", hod_views.manage_tootia, name='manage_tootia'),
    path("drug/manage/", hod_views.manage_drug, name='manage_drug'),
    path("gen/manage/", hod_views.manage_gen, name='manage_gen'),
    path("iron/manage/", hod_views.manage_iron, name='manage_iron'),
    path("ptro/manage/", hod_views.manage_ptro, name='manage_ptro'),
    path("agriculture/manage/", hod_views.manage_agriculture, name='manage_agriculture'),
    path("research/manage/", hod_views.manage_research, name='manage_research'),
    path("organ/manage/", hod_views.manage_organ, name='manage_organ'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("organ/delete/<int:organ_id>",
         hod_views.delete_organ, name='delete_organ'),

    path("subject/delete/<int:subject_id>",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         hod_views.delete_session, name='delete_session'),

    path("sugar/delete/<int:sugar_id>",
         hod_views.delete_sugar, name='delete_sugar'),
    path("kh/delete/<int:kh_id>",
         hod_views.delete_kh, name='delete_kh'),
    path("person/delete/<int:person_id>",
         hod_views.delete_person, name='delete_person'),
    path("holding/delete/<int:holding_id>",
         hod_views.delete_holding, name='delete_holding'),
    path("piran/delete/<int:piran_id>",
         hod_views.delete_piran, name='delete_piran'),
    path("tomato/delete/<int:tomato_id>",
         hod_views.delete_tomato, name='delete_tomato'),
    path("taraghi/delete/<int:taraghi_id>",
         hod_views.delete_taraghi, name='delete_taraghi'),
    path("tootia/delete/<int:tootia_id>",
         hod_views.delete_tootia, name='delete_tootia'),
    path("drug/delete/<int:drug_id>",
         hod_views.delete_drug, name='delete_drug'),
    path("gen/delete/<int:gen_id>",
         hod_views.delete_gen, name='delete_gen'),
    path("iron/delete/<int:iron_id>",
         hod_views.delete_iron, name='delete_iron'),
    path("ptro/delete/<int:ptro_id>",
         hod_views.delete_ptro, name='delete_ptro'),
    path("agriculture/delete/<int:agriculture_id>",
         hod_views.delete_agriculture, name='delete_agriculture'),
    path("research/delete/<int:research_id>",
         hod_views.delete_research, name='delete_research'),
    path("sugar/edit/<int:sugar_id>",
         hod_views.edit_sugar, name='edit_sugar'),
    path("kh/edit/<int:kh_id>",
         hod_views.edit_kh, name='edit_kh'),
    path("person/edit/<int:person_id>",
         hod_views.edit_person, name='edit_person'),
    path("holding/edit/<int:holding_id>",
         hod_views.edit_holding, name='edit_holding'),
    path("piran/edit/<int:piran_id>",
         hod_views.edit_piran, name='edit_piran'),
    path("tomato/edit/<int:tomato_id>",
         hod_views.edit_tomato, name='edit_tomato'),
    path("taraghi/edit/<int:taraghi_id>",
         hod_views.edit_taraghi, name='edit_taraghi'),
    path("tootia/edit/<int:tootia_id>",
         hod_views.edit_tootia, name='edit_tootia'),
    path("drug/edit/<int:drug_id>",
         hod_views.edit_drug, name='edit_drug'),
    path("gen/edit/<int:gen_id>",
         hod_views.edit_gen, name='edit_gen'),
    path("iron/edit/<int:iron_id>",
         hod_views.edit_iron, name='edit_iron'),
    path("ptro/edit/<int:ptro_id>",
         hod_views.edit_ptro, name='edit_ptro'),
    path("agriculture/edit/<int:agriculture_id>",
         hod_views.edit_agriculture, name='edit_agriculture'),
    path("research/edit/<int:research_id>",
         hod_views.edit_research, name='edit_research'),
    path("organ/edit/<int:organ_id>",
         hod_views.edit_organ, name='edit_organ'),
    path("subject/edit/<int:subject_id>",
         hod_views.edit_subject, name='edit_subject'),

    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_sugars/", staff_views.get_sugars, name='get_sugars'),

    path("staff/attendance/fetch/", staff_views.get_sugar_attendance,
         name='get_sugar_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         staff_views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_sugar_result'),
    path('staff/result/fetch/', staff_views.fetch_sugar_result,
         name='fetch_sugar_result'),

    # sugar

    path("sugar/home/", sugar_views.sugar_home, name='sugar_home'),
    path("sugar/organization/software/", sugar_views.sugar_organization_software, name='sugar_organization_software'),
    path("sugar/view/attendance/", sugar_views.sugar_view_attendance,
         name='sugar_view_attendance'),
    path("sugar/apply/leave/", sugar_views.sugar_apply_leave,
         name='sugar_apply_leave'),
    path("sugar/feedback/", sugar_views.sugar_feedback,
         name='sugar_feedback'),
    path("sugar/view/profile/", sugar_views.sugar_view_profile,
         name='sugar_view_profile'),
    path("sugar/fcmtoken/", sugar_views.sugar_fcmtoken,
         name='sugar_fcmtoken'),
    path("sugar/view/notification/", sugar_views.sugar_view_notification,
         name="sugar_view_notification"),
    path('sugar/view/result/', sugar_views.sugar_view_result,
         name='sugar_view_result'),
    path("test/", views.test, name='test'),

    # Khoy

    path("kh/home/", kh_views.kh_home, name='kh_home'),
    path("kh/organization/software/", kh_views.kh_organization_software, name='kh_organization_software'),
    path("kh/view/attendance/", kh_views.kh_view_attendance,
         name='kh_view_attendance'),
    path("kh/apply/leave/", kh_views.kh_apply_leave,
         name='kh_apply_leave'),
    path("kh/feedback/", kh_views.kh_feedback,
         name='kh_feedback'),
    path("kh/view/profile/", kh_views.kh_view_profile,
         name='kh_view_profile'),
    path("kh/fcmtoken/", kh_views.kh_fcmtoken,
         name='kh_fcmtoken'),
    path("kh/view/notification/", kh_views.kh_view_notification,
         name="kh_view_notification"),
    path('kh/view/result/', kh_views.kh_view_result,
         name='kh_view_result'),
    path("test/", views.test, name='test'),

    # person

    path("person/home/", person_views.person_home, name='person_home'),
    path("person/organization/software/", person_views.person_organization_software,
         name='person_organization_software'),
    path("person/view/attendance/", person_views.person_view_attendance,
         name='person_view_attendance'),
    path("person/apply/leave/", person_views.person_apply_leave,
         name='person_apply_leave'),
    path("person/feedback/", person_views.person_feedback,
         name='person_feedback'),
    path("person/view/profile/", person_views.person_view_profile,
         name='person_view_profile'),
    path("person/fcmtoken/", person_views.person_fcmtoken,
         name='person_fcmtoken'),
    path("person/view/notification/", person_views.person_view_notification,
         name="person_view_notification"),
    path('person/view/result/', person_views.person_view_result,
         name='person_view_result'),
    path("test/", views.test, name='test'),

    # holding

    path("holding/home/", holding_views.holding_home, name='holding_home'),
    path("holding/organization/software/", holding_views.holding_organization_software,
         name='holding_organization_software'),
    path("holding/view/attendance/", holding_views.holding_view_attendance,
         name='holding_view_attendance'),
    path("holding/apply/leave/", holding_views.holding_apply_leave,
         name='holding_apply_leave'),
    path("holding/feedback/", holding_views.holding_feedback,
         name='holding_feedback'),
    path("holding/view/profile/", holding_views.holding_view_profile,
         name='holding_view_profile'),
    path("holding/fcmtoken/", holding_views.holding_fcmtoken,
         name='holding_fcmtoken'),
    path("holding/view/notification/", holding_views.holding_view_notification,
         name="holding_view_notification"),
    path('holding/view/result/', holding_views.holding_view_result,
         name='holding_view_result'),
    path("test/", views.test, name='test'),

    # piran shahr

    path("piran/home/", piran_views.piran_home, name='piran_home'),
    path("piran/organization/software/", piran_views.piran_organization_software, name='piran_organization_software'),
    path("piran/view/attendance/", piran_views.piran_view_attendance,
         name='piran_view_attendance'),
    path("piran/apply/leave/", piran_views.piran_apply_leave,
         name='piran_apply_leave'),
    path("piran/feedback/", piran_views.piran_feedback,
         name='piran_feedback'),
    path("piran/view/profile/", piran_views.piran_view_profile,
         name='piran_view_profile'),
    path("piran/fcmtoken/", piran_views.piran_fcmtoken,
         name='piran_fcmtoken'),
    path("piran/view/notification/", piran_views.piran_view_notification,
         name="piran_view_notification"),
    path('piran/view/result/', piran_views.piran_view_result,
         name='piran_view_result'),
    path("test/", views.test, name='test'),

    # tomato(golfam)

    path("tomato/home/", tomato_views.tomato_home, name='tomato_home'),
    path("tomato/organization/software/", tomato_views.tomato_organization_software,
         name='tomato_organization_software'),
    path("tomato/view/attendance/", tomato_views.tomato_view_attendance,
         name='tomato_view_attendance'),
    path("tomato/apply/leave/", tomato_views.tomato_apply_leave,
         name='tomato_apply_leave'),
    path("tomato/feedback/", tomato_views.tomato_feedback,
         name='tomato_feedback'),
    path("tomato/view/profile/", tomato_views.tomato_view_profile,
         name='tomato_view_profile'),
    path("tomato/fcmtoken/", tomato_views.tomato_fcmtoken,
         name='tomato_fcmtoken'),
    path("tomato/view/notification/", tomato_views.tomato_view_notification,
         name="tomato_view_notification"),
    path('tomato/view/result/', tomato_views.tomato_view_result,
         name='tomato_view_result'),
    path("test/", views.test, name='test'),

    # taraghi shahr

    path("taraghi/home/", taraghi_views.taraghi_home, name='taraghi_home'),
    path("taraghi/organization/software/", taraghi_views.taraghi_organization_software,
         name='taraghi_organization_software'),
    path("taraghi/view/attendance/", taraghi_views.taraghi_view_attendance,
         name='taraghi_view_attendance'),
    path("taraghi/apply/leave/", taraghi_views.taraghi_apply_leave,
         name='taraghi_apply_leave'),
    path("taraghi/feedback/", taraghi_views.taraghi_feedback,
         name='taraghi_feedback'),
    path("taraghi/view/profile/", taraghi_views.taraghi_view_profile,
         name='taraghi_view_profile'),
    path("taraghi/fcmtoken/", taraghi_views.taraghi_fcmtoken,
         name='taraghi_fcmtoken'),
    path("taraghi/view/notification/", taraghi_views.taraghi_view_notification,
         name="taraghi_view_notification"),
    path('taraghi/view/result/', taraghi_views.taraghi_view_result,
         name='taraghi_view_result'),
    path("test/", views.test, name='test'),

    # tootia shahr

    path("tootia/home/", tootia_views.tootia_home, name='tootia_home'),
    path("tootia/organization/software/", tootia_views.tootia_organization_software,
         name='tootia_organization_software'),
    path("tootia/view/attendance/", tootia_views.tootia_view_attendance,
         name='tootia_view_attendance'),
    path("tootia/apply/leave/", tootia_views.tootia_apply_leave,
         name='tootia_apply_leave'),
    path("tootia/feedback/", tootia_views.tootia_feedback,
         name='tootia_feedback'),
    path("tootia/view/profile/", tootia_views.tootia_view_profile,
         name='tootia_view_profile'),
    path("tootia/fcmtoken/", tootia_views.tootia_fcmtoken,
         name='tootia_fcmtoken'),
    path("tootia/view/notification/", tootia_views.tootia_view_notification,
         name="tootia_view_notification"),
    path('tootia/view/result/', tootia_views.tootia_view_result,
         name='tootia_view_result'),
    path("test/", views.test, name='test'),

    # drug shahr

    path("drug/home/", drug_views.drug_home, name='drug_home'),
    path("drug/organization/software/", drug_views.drug_organization_software,
         name='drug_organization_software'),
    path("drug/view/attendance/", drug_views.drug_view_attendance,
         name='drug_view_attendance'),
    path("drug/apply/leave/", drug_views.drug_apply_leave,
         name='drug_apply_leave'),
    path("drug/feedback/", drug_views.drug_feedback,
         name='drug_feedback'),
    path("drug/view/profile/", drug_views.drug_view_profile,
         name='drug_view_profile'),
    path("drug/fcmtoken/", drug_views.drug_fcmtoken,
         name='drug_fcmtoken'),
    path("drug/view/notification/", drug_views.drug_view_notification,
         name="drug_view_notification"),
    path('drug/view/result/', drug_views.drug_view_result,
         name='drug_view_result'),
    path("test/", views.test, name='test'),

    # gen shahr

    path("gen/home/", gen_views.gen_home, name='gen_home'),
    path("gen/organization/software/", gen_views.gen_organization_software,
         name='gen_organization_software'),
    path("gen/view/attendance/", gen_views.gen_view_attendance,
         name='gen_view_attendance'),
    path("gen/apply/leave/", gen_views.gen_apply_leave,
         name='gen_apply_leave'),
    path("gen/feedback/", gen_views.gen_feedback,
         name='gen_feedback'),
    path("gen/view/profile/", gen_views.gen_view_profile,
         name='gen_view_profile'),
    path("gen/fcmtoken/", gen_views.gen_fcmtoken,
         name='gen_fcmtoken'),
    path("gen/view/notification/", gen_views.gen_view_notification,
         name="gen_view_notification"),
    path('gen/view/result/', gen_views.gen_view_result,
         name='gen_view_result'),
    path("test/", views.test, name='test'),

    # iron shahr

    path("iron/home/", iron_views.iron_home, name='iron_home'),
    path("iron/organization/software/", iron_views.iron_organization_software,
         name='iron_organization_software'),
    path("iron/view/attendance/", iron_views.iron_view_attendance,
         name='iron_view_attendance'),
    path("iron/apply/leave/", iron_views.iron_apply_leave,
         name='iron_apply_leave'),
    path("iron/feedback/", iron_views.iron_feedback,
         name='iron_feedback'),
    path("iron/view/profile/", iron_views.iron_view_profile,
         name='iron_view_profile'),
    path("iron/fcmtoken/", iron_views.iron_fcmtoken,
         name='iron_fcmtoken'),
    path("iron/view/notification/", iron_views.iron_view_notification,
         name="iron_view_notification"),
    path('iron/view/result/', iron_views.iron_view_result,
         name='iron_view_result'),
    path("test/", views.test, name='test'),

    # ptro shahr

    path("ptro/home/", ptro_views.ptro_home, name='ptro_home'),
    path("ptro/organization/software/", ptro_views.ptro_organization_software,
         name='ptro_organization_software'),
    path("ptro/view/attendance/", ptro_views.ptro_view_attendance,
         name='ptro_view_attendance'),
    path("ptro/apply/leave/", ptro_views.ptro_apply_leave,
         name='ptro_apply_leave'),
    path("ptro/feedback/", ptro_views.ptro_feedback,
         name='ptro_feedback'),
    path("ptro/view/profile/", ptro_views.ptro_view_profile,
         name='ptro_view_profile'),
    path("ptro/fcmtoken/", ptro_views.ptro_fcmtoken,
         name='ptro_fcmtoken'),
    path("ptro/view/notification/", ptro_views.ptro_view_notification,
         name="ptro_view_notification"),
    path('ptro/view/result/', ptro_views.ptro_view_result,
         name='ptro_view_result'),
    path("test/", views.test, name='test'),

    # agriculture shahr

    path("agriculture/home/", agriculture_views.agriculture_home, name='agriculture_home'),
    path("agriculture/organization/software/", agriculture_views.agriculture_organization_software,
         name='agriculture_organization_software'),
    path("agriculture/view/attendance/", agriculture_views.agriculture_view_attendance,
         name='agriculture_view_attendance'),
    path("agriculture/apply/leave/", agriculture_views.agriculture_apply_leave,
         name='agriculture_apply_leave'),
    path("agriculture/feedback/", agriculture_views.agriculture_feedback,
         name='agriculture_feedback'),
    path("agriculture/view/profile/", agriculture_views.agriculture_view_profile,
         name='agriculture_view_profile'),
    path("agriculture/fcmtoken/", agriculture_views.agriculture_fcmtoken,
         name='agriculture_fcmtoken'),
    path("agriculture/view/notification/", agriculture_views.agriculture_view_notification,
         name="agriculture_view_notification"),
    path('agriculture/view/result/', agriculture_views.agriculture_view_result,
         name='agriculture_view_result'),
    path("test/", views.test, name='test'),

    # research shahr

    path("research/home/", research_views.research_home, name='research_home'),
    path("research/organization/software/", research_views.research_organization_software,
         name='research_organization_software'),
    path("research/view/attendance/", research_views.research_view_attendance,
         name='research_view_attendance'),
    path("research/apply/leave/", research_views.research_apply_leave,
         name='research_apply_leave'),
    path("research/feedback/", research_views.research_feedback,
         name='research_feedback'),
    path("research/view/profile/", research_views.research_view_profile,
         name='research_view_profile'),
    path("research/fcmtoken/", research_views.research_fcmtoken,
         name='research_fcmtoken'),
    path("research/view/notification/", research_views.research_view_notification,
         name="research_view_notification"),
    path('research/view/result/', research_views.research_view_result,
         name='research_view_result'),
    path("test/", views.test, name='test'),

    # user change picture and password

    # sugar(ghand_orumiye)
    path("manage/sugar/change/password/picture/", sugar_views.manage_sugar_change_password_picture,
         name='manage_sugar_change_password_picture'),

    path("sugar/edit/user/password/<int:sugar_id>/", sugar_views.edit_sugar_user_password,
         name='edit_sugar_user_password'),
    path("sugar/edit/user/picture/<int:sugar_id>/", sugar_views.edit_sugar_user_picture,
         name='edit_sugar_user_picture'),

    # person
    path("manage_person_change_password/", person_views.manage_person_change_password,
         name='manage_person_change_password'),
    path("person/edit/user/password/<int:person_id>/", person_views.edit_person_user_password,
         name='edit_person_user_password'),
    path("person/edit/user/picture/<int:person_id>/", person_views.edit_person_user_picture,
         name='edit_person_user_picture'),

    # holding
    path("manage_holding_change_password/", holding_views.manage_holding_change_password,
         name='manage_holding_change_password'),
    path("holding/edit/user/password/<int:holding_id>/", holding_views.edit_holding_user_password,
         name='edit_holding_user_password'),
    path("holding/edit/user/picture/<int:holding_id>/", holding_views.edit_holding_user_picture,
         name='edit_holding_user_picture'),

    # khoy
    path("manage_kh_change_password/", kh_views.manage_kh_change_password, name='manage_kh_change_password'),
    path("kh/edit/user/password/<int:kh_id>/", kh_views.edit_kh_user_password, name='edit_kh_user_password'),
    path("kh/edit/user/picture/<int:kh_id>/", kh_views.edit_kh_user_picture, name='edit_kh_user_picture'),

    # piran
    path("manage_piran_change_password/", piran_views.manage_piran_change_password_picture,
         name='manage_piran_change_password'),
    path("piran/edit/user/password/<int:piran_id>/", piran_views.edit_piran_user_password,
         name='edit_piran_user_password'),
    path("piran/edit/user/picture/<int:piran_id>/", piran_views.edit_piran_user_picture,
         name='edit_piran_user_picture'),

    # tomato(golfam) user change picture and password
    path("manage/tomato/change/password/picture/", tomato_views.manage_tomato_change_password_picture,
         name='manage_tomato_change_password_picture'),
    path("tomato/edit/user/password/<int:tomato_id>/", tomato_views.edit_tomato_user_password,
         name='edit_tomato_user_password'),
    path("tomato/edit/user/picture/<int:tomato_id>/", tomato_views.edit_tomato_user_picture,
         name='edit_tomato_user_picture'),

    # tootia(golfam) user change picture and password
    path("manage/tootia/change/password/picture/", tootia_views.manage_tootia_change_password_picture,
         name='manage_tootia_change_password_picture'),
    path("tootia/edit/user/password/<int:tootia_id>/", tootia_views.edit_tootia_user_password,
         name='edit_tootia_user_password'),
    path("tootia/edit/user/picture/<int:tootia_id>/", tootia_views.edit_tootia_user_picture,
         name='edit_tootia_user_picture'),

    # tootia user change picture and password
    path("manage/tootia/change/password/picture/", tootia_views.manage_tootia_change_password_picture,
         name='manage_tootia_change_password_picture'),
    path("tootia/edit/user/password/<int:tootia_id>/", tootia_views.edit_tootia_user_password,
         name='edit_tootia_user_password'),
    path("tootia/edit/user/picture/<int:tootia_id>/", tootia_views.edit_tootia_user_picture,
         name='edit_tootia_user_picture'),

    # ptro(petroshimi) user change picture and password
    path("manage/ptro/change/password/picture/", ptro_views.manage_ptro_change_password_picture,
         name='manage_ptro_change_password_picture'),
    path("ptro/edit/user/password/<int:ptro_id>/", ptro_views.edit_ptro_user_password,
         name='edit_ptro_user_password'),
    path("ptro/edit/user/picture/<int:ptro_id>/", ptro_views.edit_ptro_user_picture,
         name='edit_ptro_user_picture'),

    # agriculture user change picture and password
    path("manage/agriculture/change/password/picture/", agriculture_views.manage_agriculture_change_password_picture,
         name='manage_agriculture_change_password_picture'),
    path("agriculture/edit/user/password/<int:agriculture_id>/", agriculture_views.edit_agriculture_user_password,
         name='edit_agriculture_user_password'),
    path("agriculture/edit/user/picture/<int:agriculture_id>/", agriculture_views.edit_agriculture_user_picture,
         name='edit_agriculture_user_picture'),

    # research user change picture and password
    path("manage/research/change/password/picture/", research_views.manage_research_change_password_picture,
         name='manage_research_change_password_picture'),
    path("research/edit/user/password/<int:research_id>", research_views.edit_research_user_password,
         name='edit_research_user_password'),
    path("research/edit/user/picture/<int:research_id>", research_views.edit_research_user_picture,
         name='edit_research_user_picture'),

    # iron user change picture and password
    path("manage/iron/change/password/picture/", iron_views.manage_iron_change_password_picture,
         name='manage_iron_change_password_picture'),
    path("iron/edit/user/password/<int:iron_id>/", iron_views.edit_iron_user_password,
         name='edit_iron_user_password'),
    path("iron/edit/user/picture/<int:iron_id>/", iron_views.edit_iron_user_picture,
         name='edit_iron_user_picture'),

    # drug(golfam daroo) user change picture and password
    path("manage/drug/change/password/picture/", drug_views.manage_drug_change_password_picture,
         name='manage_drug_change_password_picture'),
    path("drug/edit/user/password/<int:drug_id>/", drug_views.edit_drug_user_password,
         name='edit_drug_user_password'),
    path("drug/edit/user/picture/<int:drug_id>/", drug_views.edit_drug_user_picture,
         name='edit_drug_user_picture'),

    # gen(shafazhen) user change picture and password
    path("manage/gen/change/password/picture/", gen_views.manage_gen_change_password_picture,
         name='manage_gen_change_password_picture'),
    path("gen/edit/user/password/<int:gen_id>", gen_views.edit_gen_user_password,
         name='edit_gen_user_password'),
    path("gen/edit/user/picture/<int:gen_id>", gen_views.edit_gen_user_picture,
         name='edit_gen_user_picture'),

    # taraghi
    path("manage_taraghi_change_password/", taraghi_views.manage_taraghi_change_password_picture,
         name='manage_taraghi_change_password_picture'),
    path("taraghi/edit/user/password/<int:taraghi_id>", taraghi_views.edit_taraghi_user_password,
         name='edit_taraghi_user_password'),
    path("taraghi/edit/user/picture/<int:taraghi_id>", taraghi_views.edit_taraghi_user_picture,
         name='edit_taraghi_user_picture'),

    # news
    path("all/news/", all_views.all_news,
         name='all_news'),
    path("all/news/1/", all_views.all_news_1,
         name='all_news_1'),
    path("all/news/2/", all_views.all_news_2,
         name='all_news_2'),
    path("all/news/3/", all_views.all_news_3,
         name='all_news_3'),
    path("all/news/4/", all_views.all_news_4,
         name='all_news_4'),
    path("all/news/5/", all_views.all_news_5,
         name='all_news_5'),
    path("all/news/6/", all_views.all_news_6,
         name='all_news_6'),
    path("all/news/7/", all_views.all_news_7,
         name='all_news_7'),
    path("all/news/8/", all_views.all_news_8,
         name='all_news_8'),
    path("all/news/9/", all_views.all_news_9,
         name='all_news_9'),
    path("all/news/10/", all_views.all_news_10,
         name='all_news_10'),
    path("all/news/11/", all_views.all_news_11,
         name='all_news_11'),
    path("all/news/12/", all_views.all_news_12,
         name='all_news_12'),

    path("person/news/", person_views.person_news,
         name='person_news'),

    path("person/news/", person_views.person_news,
         name='person_news'),

    # admin upload file
    path('index/', hod_views.index, name='index'),

    # user upload file
    path('user/index/', all_views.user_index, name='user_index'),

    # download file(فیش حقوقی)

    # sugar download file
    path("sugar/user/download/file/", sugar_views.sugar_user_download_file,
         name='sugar_user_download_file'),

    # person download file
    path("person/user/download/file/", person_views.person_user_download_file,
         name='person_user_download_file'),

    # holding download file
    path("holding/user/download/file/", holding_views.holding_user_download_file,
         name='holding_user_download_file'),

    # all
    path("person/fcmtoken/", all_views.all_fcmtoken,
         name='all_fcmtoken'),

    # all
    path("holding/fcmtoken/", all_views.all_fcmtoken,
         name='all_fcmtoken'),

    # fish hoghughi
    path("all/user/download/file/", all_views.all_user_download_file,
         name='all_user_download_file'),

    # all websites
    path("all/websites/", all_views.all_websites,
         name='all_websites'),

    # all update profile
    path("manage/all/change/password/image/", all_views.manage_all_change_password_image,
         name='manage_all_change_password_image'),
    path("all/edit/user/password/<int:all_id>/", all_views.edit_all_user_password, name='edit_all_user_password'),
    path("all/edit/user/picture/<int:all_id>/", all_views.edit_all_user_picture, name='edit_all_user_picture'),

    # /reset/password/
    path("reset_password/", all_views.reset_password, name='reset_password'),
    path("do_reset_password/", all_views.do_reset_password, name='do_reset_password'),

    # social media
    path("social/media/", all_views.social_media,
         name='social_media'),

    # fish hoghughi
    path("user/traffic/control/", all_views.user_traffic_control,
         name='user_traffic_control'),

    # all_in_progress
    path("all/in/progress/1/", all_views.all_in_progress_1,
         name='all_in_progress_1'),
    path("all/in/progress/2/", all_views.all_in_progress_2,
         name='all_in_progress_2'),
    path("all/in/progress/3/", all_views.all_in_progress_3,
         name='all_in_progress_3'),
    path("all/in/progress/4/", all_views.all_in_progress_4,
         name='all_in_progress_4'),
    path("all/in/progress/5/", all_views.all_in_progress_5,
         name='all_in_progress_5'),
    path("all/in/progress/6/", all_views.all_in_progress_6,
         name='all_in_progress_6'),
    path("all/in/progress/7/", all_views.all_in_progress_7,
         name='all_in_progress_7'),
    path("all/in/progress/8/", all_views.all_in_progress_8,
         name='all_in_progress_8'),
    path("all/in/progress/9/", all_views.all_in_progress_9,
         name='all_in_progress_9'),
    path("all/in/progress/10/", all_views.all_in_progress_10,
         name='all_in_progress_10'),

    # organizational chart
    path("organizational/chart/", all_views.organizational_chart,
         name='organizational_chart'),

    # related organizations
    path("related/organizations/", all_views.related_organizations,
         name='related_organizations'),

    # companies phone numbers
    path("companies/phone/numbers/", all_views.companies_phone_numbers,
         name='companies_phone_numbers'),
    path("shahd/phone/numbers/", all_views.shahd_phone_numbers,
         name='shahd_phone_numbers'),
    path("sugar/phone/numbers/", all_views.sugar_phone_numbers,
         name='sugar_phone_numbers'),
    path("kh/phone/numbers/", all_views.kh_phone_numbers,
         name='kh_phone_numbers'),
    path("piran/phone/numbers/", all_views.piran_phone_numbers,
         name='piran_phone_numbers'),

    path("tomato/phone/numbers/", all_views.tomato_phone_numbers,
         name='tomato_phone_numbers'),
    path("taraghi/phone/numbers/", all_views.taraghi_phone_numbers,
         name='taraghi_phone_numbers'),
    path("tootia/phone/numbers/", all_views.tootia_phone_numbers,
         name='tootia_phone_numbers'),
    path("drug/phone/numbers/", all_views.drug_phone_numbers,
         name='drug_phone_numbers'),
    path("gen/phone/numbers/", all_views.gen_phone_numbers,
         name='gen_phone_numbers'),
    path("iron/phone/numbers/", all_views.iron_phone_numbers,
         name='iron_phone_numbers'),
    path("ptro/phone/numbers/", all_views.ptro_phone_numbers,
         name='ptro_phone_numbers'),
    path("agriculture/phone/numbers/", all_views.agriculture_phone_numbers,
         name='agriculture_phone_numbers'),
    path("research/phone/numbers/", all_views.research_phone_numbers,
         name='research_phone_numbers'),

    path("device/panel/", all_views.DevicePanel.as_view(), name='device_panel'),
    path("device/panel/create/", all_views.DevicePanelCreate.as_view(), name='device_panel_create'),
    path("device/panel/source/destination/", all_views.DevicePanelSourceDestination.as_view(), name='device_panel_source_destination'),
]

urlpatterns += [
    path('news/<str:news_id>/view/', increment_view, name='increment_view'),
    path('news/<str:news_id>/count/', get_view_count, name='get_view_count'),
]