# Generated by Django 3.1.1 on 2024-08-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240814_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='Staff_Khoy',
        ),
    ]
