# Generated by Django 3.1.1 on 2024-08-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_kh_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReportKh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.kh')),
            ],
        ),
    ]
