# Generated by Django 3.1.1 on 2024-08-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_leavereportkh'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackKh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.kh')),
            ],
        ),
    ]
