# Generated by Django 3.1.1 on 2024-08-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_feedbackkh'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationKh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.kh')),
            ],
        ),
        migrations.CreateModel(
            name='KhResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FloatField(default=0)),
                ('exam', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.kh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
        ),
    ]
