# Generated by Django 3.1.1 on 2024-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_notificationstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportpiran',
            name='piran',
        ),
        migrations.RemoveField(
            model_name='notificationpiran',
            name='piran',
        ),
        migrations.RemoveField(
            model_name='piran',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='piran',
            name='course',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Kh')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='FeedbackPiran',
        ),
        migrations.DeleteModel(
            name='LeaveReportPiran',
        ),
        migrations.DeleteModel(
            name='NotificationPiran',
        ),
        migrations.DeleteModel(
            name='Piran',
        ),
    ]
