# Generated by Django 3.1.1 on 2024-09-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20240907_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='piran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.piran'),
        ),
    ]
