# Generated by Django 3.1.1 on 2024-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_attendancereport_piran'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackStudent',
            new_name='FeedbackSugar',
        ),
        migrations.RenameModel(
            old_name='LeaveReportStudent',
            new_name='LeaveReportSugar',
        ),
        migrations.RenameModel(
            old_name='NotificationStudent',
            new_name='NotificationSugar',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Sugar',
        ),
        migrations.RenameModel(
            old_name='StudentResult',
            new_name='SugarResult',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='student',
            new_name='sugar',
        ),
        migrations.RenameField(
            model_name='feedbacksugar',
            old_name='student',
            new_name='sugar',
        ),
        migrations.RenameField(
            model_name='leavereportsugar',
            old_name='student',
            new_name='super',
        ),
        migrations.RenameField(
            model_name='notificationsugar',
            old_name='student',
            new_name='sugar',
        ),
        migrations.RenameField(
            model_name='sugarresult',
            old_name='student',
            new_name='sugar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Sugar'), (4, 'Kh'), (5, 'Holding'), (6, 'Piran')], default=1, max_length=1),
        ),
    ]
