# Generated by Django 3.1.1 on 2024-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20240925_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportsugar',
            old_name='super',
            new_name='sugar',
        ),
    ]
