# Generated by Django 5.1.4 on 2025-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
