# Generated by Django 5.1.4 on 2025-01-05 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_student_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='gregorian_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 10, 31, 47, 793294)),
        ),
        migrations.AddField(
            model_name='student',
            name='jalali_date',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
    ]
