# Generated by Django 5.1.4 on 2025-01-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_remove_student_date_student_gregorian_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gregorian_date',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 10, 38, 9, 287857)),
        ),
    ]
