# Generated by Django 5.1.4 on 2025-01-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_student_subject_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPasswordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('new_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 6, 13, 30, 27, 285057)),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
