# Generated by Django 5.1.4 on 2025-01-11 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_flag_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login', models.DateTimeField(auto_now_add=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('actions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 34, 48, 850603)),
        ),
    ]
