# Generated by Django 5.1.4 on 2025-01-11 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_usernamelog_alter_student_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsernameLog',
            new_name='UserLog',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 13, 36, 51, 192685)),
        ),
    ]
