# Generated by Django 5.1.4 on 2025-02-04 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_rename_usernamelog_userlog_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.IntegerField(unique=True)),
                ('access_level_number', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('passwords_history', models.JSONField(default=list)),
                ('wrong_passwords_number', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=32, null=True)),
                ('home_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('internal_company_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=32)),
                ('home_address', models.CharField(blank=True, max_length=256, null=True)),
                ('company_address', models.CharField(blank=True, max_length=256, null=True)),
                ('main_profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('all_profile_images', models.JSONField(default=list)),
                ('company', models.CharField(choices=[('ShahdGroup', 'گروه توسعه صنایع شهد آذربایجان'), ('UrmiaSugar', 'چغندر قند ارومیه'), ('KhoySugar', 'قند خوی'), ('PiraSugar', 'قند پیرانشهر'), ('TaraghiShop', 'فروشگاه های زنجیره ای ترقی'), ('Golfam', 'گلفام'), ('GolfamDaru', 'گلفام دارو'), ('Tootia', 'صنایع توسعه شهد توتیا'), ('Ssnsco', 'داروگستر ساوا شفاژن'), ('UrmiaResearch', 'تحقیقات و خدمات فنی مکانیزه چغندر قند ارومیه'), ('UrmiaAgriculture', 'تحقیقات و خدمات کشاورزی و بهزراعی آذربایجان غربی'), ('nwsi', 'صنایع ذوب آهن شمالغرب'), ('Petrochemical', 'پتروشیمی')], default='ShahdGroup', max_length=32)),
                ('login_ip_address', models.JSONField(default=list)),
                ('gregorian_datetime_create', models.DateTimeField(auto_now_add=True)),
                ('gregorian_datetime_delete', models.DateTimeField(blank=True, null=True)),
                ('jalili_datetime_create', models.DateTimeField(blank=True, null=True)),
                ('jalili_datetime_delete', models.DateTimeField(blank=True, null=True)),
                ('gregorian_logins_datetime', models.JSONField(default=list)),
                ('gregorian_logouts_datetime', models.JSONField(default=list)),
                ('jalili_logins_datetime', models.JSONField(default=list)),
                ('jalili_logouts_datetime', models.JSONField(default=list)),
                ('gregorian_birthday_datetime', models.DateTimeField(blank=True, null=True)),
                ('jalili_birthday_datetime', models.DateTimeField(blank=True, null=True)),
                ('files_upload', models.JSONField(default=list)),
                ('files_download', models.JSONField(default=list)),
                ('security_question_answer', models.JSONField(default=list)),
                ('Actions', models.JSONField(default=list)),
                ('national_code', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=32, null=True)),
                ('work_experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('awards_and_Honors', models.JSONField(default=list)),
                ('experiences', models.JSONField(default=list)),
                ('instagram_username', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=32, null=True)),
                ('whatsapp_id', models.CharField(blank=True, max_length=32, null=True)),
                ('other_social_media', models.JSONField(default=list)),
                ('house_location_x', models.CharField(blank=True, max_length=32, null=True)),
                ('house_location_y', models.CharField(blank=True, max_length=32, null=True)),
                ('company_location_x', models.CharField(blank=True, max_length=32, null=True)),
                ('company_location_y', models.CharField(blank=True, max_length=32, null=True)),
                ('chat_history', models.JSONField(default=list)),
                ('residence_country', models.CharField(blank=True, max_length=32, null=True)),
                ('residence_city', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=32, null=True)),
                ('comments', models.JSONField(default=list)),
                ('documents', models.JSONField(default=list)),
                ('family_numbers', models.IntegerField(blank=True, null=True)),
                ('managers', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 10, 48, 35, 71767)),
        ),
    ]
