# Generated by Django 5.1.4 on 2025-02-04 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gregorian_datetime_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 11, 1, 28, 348623)),
        ),
    ]
