# Generated by Django 5.1.4 on 2025-02-04 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_alter_person_gregorian_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 11, 2, 4, 701981)),
        ),
    ]
