# Generated by Django 5.1.4 on 2025-02-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_alter_person_gregorian_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 11, 46, 39, 571137)),
        ),
    ]
