# Generated by Django 5.1.4 on 2025-02-04 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 14, 43, 52, 138582)),
        ),
    ]
