# Generated by Django 5.1.4 on 2025-02-04 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_alter_person_passwords_history_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Actions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='all_profile_images',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='awards_and_Honors',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='chat_history',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='documents',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='experiences',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='files_download',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='files_upload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gregorian_logins_datetime',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gregorian_logouts_datetime',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='jalili_logins_datetime',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='jalili_logouts_datetime',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='login_ip_address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='managers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_social_media',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='security_question_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_experience',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 15, 6, 57, 290982)),
        ),
    ]
