# Generated by Django 5.1.4 on 2025-02-04 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_alter_person_company_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Actions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='awards_and_Honors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='chat_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, choices=[('ShahdGroup', 'گروه توسعه صنایع شهد آذربایجان'), ('UrmiaSugar', 'چغندر قند ارومیه'), ('KhoySugar', 'قند خوی'), ('PiraSugar', 'قند پیرانشهر'), ('TaraghiShop', 'فروشگاه های زنجیره ای ترقی'), ('Golfam', 'گلفام'), ('GolfamDaru', 'گلفام دارو'), ('Tootia', 'صنایع توسعه شهد توتیا'), ('Ssnsco', 'داروگستر ساوا شفاژن'), ('UrmiaResearch', 'تحقیقات و خدمات فنی مکانیزه چغندر قند ارومیه'), ('UrmiaAgriculture', 'تحقیقات و خدمات کشاورزی و بهزراعی آذربایجان غربی'), ('nwsi', 'صنایع ذوب آهن شمالغرب'), ('Petrochemical', 'پتروشیمی')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='experiences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='files_download',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='files_upload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gregorian_logins_datetime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gregorian_logouts_datetime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='jalili_logins_datetime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='jalili_logouts_datetime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='login_ip_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='managers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_social_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='security_question_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='wrong_passwords_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 15, 13, 7, 875941)),
        ),
    ]
