# Generated by Django 5.1.4 on 2025-02-04 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 15, 30, 2, 396634)),
        ),
    ]
