# Generated by Django 5.1.4 on 2025-02-05 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 9, 50, 17, 949213)),
        ),
    ]
