# Generated by Django 5.1.4 on 2025-02-05 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_delete_person_customuser_access_level_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 10, 28, 44, 956547)),
        ),
    ]
