# Generated by Django 5.1.4 on 2025-02-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 12, 40, 51, 76572)),
        ),
    ]
