# Generated by Django 5.1.4 on 2025-02-05 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0079_alter_customuser_is_test_alter_student_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_test',
            new_name='real_person',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 13, 19, 9, 713619)),
        ),
    ]
