# Generated by Django 5.1.4 on 2025-02-05 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0080_rename_is_test_customuser_real_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='real_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 13, 29, 31, 776034)),
        ),
    ]
