# Generated by Django 5.1.4 on 2025-02-09 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0082_alter_customuser_address_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_location_x',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_location_y',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='house_location_x',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='house_location_y',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='main_profile_image',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 14, 29, 16, 866343)),
        ),
    ]
