# Generated by Django 5.1.4 on 2025-02-11 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0084_alter_customuser_user_type_alter_student_date_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Sugar'), (4, 'Kh'), (20, 'Person'), (5, 'Holding'), (6, 'Piran'), (7, 'Tomato'), (8, 'Taraghi'), (9, 'Tootia'), (10, 'Drug'), (11, 'Gen'), (12, 'Iron'), (13, 'Ptro'), (14, 'Agriculture'), (15, 'research')], default=20, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 11, 8, 19, 52, 321550)),
        ),
    ]
