# Generated by Django 5.1.4 on 2025-02-11 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0086_alter_customuser_company_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 11, 13, 45, 28, 634676)),
        ),
    ]
