# Generated by Django 5.1.4 on 2025-02-16 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0087_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 16, 16, 6, 47, 863009)),
        ),
    ]
