# Generated by Django 5.1.4 on 2025-02-16 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0088_customuser_post_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 16, 16, 25, 35, 888301)),
        ),
    ]
