# Generated by Django 5.1.4 on 2025-02-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0089_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, choices=[('Person', 'پرسون'), ('ShahdGroup', 'گروه توسعه صنایع شهد آذربایجان'), ('UrmiaSugar', 'قند ارومیه'), ('KhoySugar', 'قند خوی'), ('PiraSugar', 'قند پیرانشهر'), ('TaraghiShop', 'فروشگاه های زنجیره ای ترقی'), ('Golfam', 'گلفام'), ('GolfamDaru', 'گلفام دارو'), ('Tootia', 'صنایع توسعه شهد توتیا'), ('Ssnsco', 'داروگستر ساوا شفاژن'), ('UrmiaResearch', 'تحقیقات و خدمات فنی مکانیزه چغندر قند ارومیه'), ('UrmiaAgriculture', 'تحقیقات و خدمات کشاورزی و بهزراعی آذربایجان غربی'), ('nwsi', 'صنایع ذوب آهن شمالغرب'), ('Petrochemical', 'پتروشیمی')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 17, 10, 30, 15, 559174)),
        ),
    ]
