# Generated by Django 5.1.4 on 2025-02-17 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0090_alter_customuser_company_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 17, 10, 32, 48, 529940)),
        ),
    ]
