# Generated by Django 5.1.4 on 2025-02-24 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0092_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='month_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 24, 13, 1, 12, 675472)),
        ),
    ]
