# Generated by Django 5.1.2 on 2025-02-25 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0093_student_month_counter_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 25, 15, 56, 29, 897586)),
        ),
    ]
