# Generated by Django 5.1.4 on 2025-04-05 12:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0094_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('owner', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('department', models.CharField(blank=True, max_length=32, null=True)),
                ('room', models.CharField(blank=True, max_length=32, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('building_unit', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 5, 16, 12, 52, 934398)),
        ),
        migrations.CreateModel(
            name='DeviceTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_datetime', models.DateTimeField(blank=True, null=True)),
                ('destination_datetime', models.DateTimeField(blank=True, null=True)),
                ('destination_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_transfer_destination_person', to=settings.AUTH_USER_MODEL)),
                ('devide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.device')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_transfer_source_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
