# Generated by Django 5.1.4 on 2025-04-05 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0095_device_alter_student_date_devicetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_panel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 5, 16, 20, 14, 144362)),
        ),
    ]
