# Generated by Django 5.1.4 on 2025-04-07 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0097_alter_customuser_user_type_alter_student_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='owner',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='owner_email',
        ),
        migrations.RenameField(
            model_name='devicetransfer',
            old_name='destination_datetime',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='building_unit',
        ),
        migrations.RemoveField(
            model_name='devicetransfer',
            name='destination_person',
        ),
        migrations.RemoveField(
            model_name='devicetransfer',
            name='devide',
        ),
        migrations.RemoveField(
            model_name='devicetransfer',
            name='source_datetime',
        ),
        migrations.RemoveField(
            model_name='devicetransfer',
            name='source_person',
        ),
        migrations.AddField(
            model_name='device',
            name='owner_firstname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_lastname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='user_email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='destination_person_email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='destination_person_first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='destination_person_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='device_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='device_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='source_person_email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='source_person_first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='source_person_last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicetransfer',
            name='transfer_time_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 7, 9, 12, 0, 576921)),
        ),
    ]
