# Generated by Django 5.1.4 on 2025-04-07 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0098_rename_owner_device_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='exist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='real',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 7, 9, 39, 15, 764118)),
        ),
    ]
