# Generated by Django 5.1.2 on 2025-04-12 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0099_device_exist_device_real_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 12, 37, 23, 110131)),
        ),
    ]
