# Generated by Django 3.1.1 on 2025-06-01 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0100_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsViewCount',
            fields=[
                ('news_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 11, 22, 9, 789398)),
        ),
    ]
