# Generated by Django 5.1.2 on 2025-06-02 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0101_auto_20250601_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 2, 8, 34, 17, 31387)),
        ),
    ]
