# Generated by Django 5.2.3 on 2025-07-12 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0101_auto_20250601_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hiring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 10, 4, 5, 417886)),
        ),
    ]
