# Generated by Django 5.2.3 on 2025-07-12 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0102_customuser_hiring_date_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 13, 32, 6, 58144)),
        ),
    ]
