# Generated by Django 5.2.3 on 2025-07-12 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0103_customuser_unit_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kh',
            name='hiring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kh',
            name='national_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kh',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 14, 9, 54, 741726)),
        ),
    ]
