# Generated by Django 5.2.3 on 2025-07-12 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0104_kh_hiring_date_kh_national_code_kh_personal_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hiring_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='kh',
            name='hiring_date',
        ),
        migrations.RemoveField(
            model_name='kh',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='kh',
            name='personal_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 14, 55, 3, 313647)),
        ),
    ]
