# Generated by Django 5.2.3 on 2025-07-12 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0105_remove_customuser_hiring_date_remove_customuser_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kh',
            name='internal_company_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kh',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 15, 8, 39, 104564)),
        ),
    ]
