# Generated by Django 5.2.3 on 2025-07-12 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0106_kh_internal_company_phone_number_kh_personal_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 15, 13, 51, 84277)),
        ),
    ]
