# Generated by Django 5.2.3 on 2025-07-14 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0108_alter_student_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kh',
            name='internal_company_phone_number',
        ),
        migrations.RemoveField(
            model_name='kh',
            name='personal_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 11, 27, 18, 225961)),
        ),
    ]
