# Generated by Django 5.2.3 on 2025-07-14 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0110_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 12, 0, 45, 275910)),
        ),
    ]
