# Generated by Django 5.1.2 on 2025-07-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0102_alter_student_date'),
        ('main_app', '0111_alter_student_date'),
    ]

    operations = [
    ]
