# Generated by Django 5.1.2 on 2025-07-16 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0112_merge_0102_alter_student_date_0111_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hiring_date',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 9, 23, 24, 959980)),
        ),
    ]
