# Generated by Django 5.1.2 on 2025-07-16 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0113_customuser_hiring_date_customuser_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personel_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 10, 56, 12, 780944)),
        ),
    ]
