# Generated by Django 5.2 on 2025-07-22 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0115_customuser_company_location_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 23, 1, 58, 939278)),
        ),
    ]
