# Generated by Django 5.2 on 2025-07-23 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0121_alter_customuser_user_type_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 21, 24, 23, 263705)),
        ),
    ]
