# Generated by Django 5.2 on 2025-07-28 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0122_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='device_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 18, 6, 10, 633562)),
        ),
    ]
