# Generated by Django 5.2 on 2025-07-28 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0123_alter_customuser_device_panel_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='device_panel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 19, 6, 31, 744223)),
        ),
    ]
